# Generated by Django 5.0.4 on 2024-04-16 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('DOB', models.DateField(blank=True, max_length=10, null=True)),
                ('Pan', models.CharField(blank=True, max_length=10, null=True)),
                ('father_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Profile_img', models.ImageField(blank=True, default='images/default_profile.png', null=True, upload_to='images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
